data:
  shapenet_dir: data/meshes/
  out_dir: data/processed/
  meshes:
    - "ffccda82ecc0d0f71740529c616cd4c7" # Airplane mesh.
  num_points: 1024
  bound: 0.5
  train_split: "train.lst"
  val_split: "val.lst"
  test_split: "test.lst"
  num_train_transforms: 100000
  num_test_transforms: 100
  rotation_max: 1.57 # pi/2
  translation_max: 0.5
  pointcloud_file: points.npz
  train_transforms_file: train_transforms.npz
  test_transforms_file: test_transforms.npz
  validation_transforms_file: validation_transforms.npz
  visualize_transforms_file: visualize_transforms.npz  
model:
  c_dim: 128
  dim: 3
  hidden_dim: 512
training:
  out_dir: out/reconstruction_model/
  epochs: 100
  batch_size: 32
  shuffle: true
  learning_rate: 0.0001
  visualize_every: 500
  validate_every: 1000
  print_every: 20
  backup_every: 500
align:
  vis_dir: out/reconstruction_align/
  vis_every: 20
  max_iters: 1000
  epsilon: 0.0001